<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />w <i>{file}</i> linia <i>{line}</i>.<br/>-- {link}' => '',
    'Action' => 'Akcja',
    'Args' => 'Argumenty',
    'Audit' => 'Audyt',
    'Audit Error in Audit Entry #{entry_id}' => 'Błąd audytu w logu #{entry_id}',
    'Audit Module' => 'Moduł audytu',
    'BCC' => '',
    'CC' => '',
    'CURL' => '',
    'Called' => 'Wywołanie',
    'Created' => 'Data dodania',
    'Data' => '',
    'Database Trails' => '',
    'Diff' => 'Różnica',
    'Difference' => 'Różnica',
    'Download' => 'Pobierz',
    'Download eml file' => 'Pobierz plik eml',
    'Duration' => 'Czas wykonania',
    'Email Messages' => 'Wiadomości e-mail',
    'Emailed' => 'Wysłane pocztą e-mail',
    'Entries' => 'Logi',
    'Entry #{id}' => 'Log #{id}',
    'Entry ID' => 'ID logu',
    'Error' => 'Błąd',
    'Error #{id}' => 'Błąd #{id}',
    'Error Code' => 'Kod błędu',
    'Errors' => 'Błędy',
    'Extra' => 'Dodatkowe',
    'Extra Data' => 'Dodatkowe dane',
    'Field' => 'Pole',
    'File' => 'Plik',
    'From' => 'Od',
    'Guest' => 'Gość',
    'HTML' => '',
    'HTML Body' => 'Treść HTML',
    'Hash' => '',
    'ID' => '',
    'IP' => '',
    'Javascript' => '',
    'Javascript #{id}' => '',
    'Javascripts' => '',
    'Line' => 'Linia',
    'Mail' => 'Mail',
    'Mail #{id}' => 'Mail #{id}',
    'Mails' => 'Maile',
    'Memory' => 'Pamieć',
    'Message' => 'Wiadomość',
    'Model ID' => 'ID modelu',
    'New Value' => 'Nowa wartość',
    'No' => 'Nie',
    'Old Value' => 'Stara wartość',
    'Origin' => 'źródło',
    'Profiling' => 'Profilowanie',
    'Reply' => 'Odpowiedź',
    'Request' => 'Zapytanie',
    'Request Method' => 'Metoda zapytania',
    'Stack Trace' => 'Stos wywołań',
    'Subject' => 'Temat',
    'Successful' => 'Wysłany',
    'Text' => 'Tekst',
    'Text Body' => 'Treść tekstowa',
    'To' => 'Do',
    'Trace' => '',
    'Trail' => 'Zmiana',
    'Trail #{id}' => 'Zmiana #{id}',
    'Trails' => 'Zmiany',
    'Type' => 'Typ',
    'User' => 'Użytkownik',
    'User ID' => 'ID użytkownika',
    'Yes' => 'Tak',
    'view audit entry' => 'zobacz wpis audytu',
    '{message}' => '',
];
